module.exports.ErrorMessage = {
  ApplicationError: "An Application Error Has Occured",
  Invalid_Request: "Invalid Request",
  Invalid_Authentication: "Invalid Authentication",
  Invalid_Request_Url: "Invalid Request URL",
  Invalid_User_Credentials: "Invalid User Credentials",
  PhoneNo_Already_Exists: "Phone number already exists",
  Email_Already_Exists: "Email Already Exists",
  User_Dont_Exists: "User Dont Exist",
  Vendor_Dont_Exists: "Vendor Dont Exists",
  Review_Already_Exists: "Review Already Exist",
  Review_Reply_Already_Exists: "Review Reply Already Exist",
  Saved_Service_Already_Exists: "Saved Service Already Exist",
  Package_Dont_Exists: "Package Dont Exist",
  Catalogue_Dont_Exists: "Catalogue Dont Exists",
  No_Reviews_Found: "No Reviews Found",
  No_Saved_Services_Available: "No Saved Services Available",
  No_Leads_Found: "No Leads Found",
  No_Vendors_Found: "No Vendors Available",
  Category_Already_Exists: "Category already  exists",
  Category_Dont_Exists: "No category found",
  Sub_Catergory_Already_Exists: "Subcatergory already Exists",
  No_Sub_Category_Found: "No Sub category found",
  No_Service_Found: "No Service Found",
  No_Notification_Found: "No Notification Found",
  Business_Dont_Exists: "Business Dont Exists",
  New_password_should_not_be_same_as_your_previous_password:
    "New password should not be same as your previous password.",
  Passwords_do_not_match: "Passwords do not match",
  Old_Password_Incorrect: "Old Password Incorrect",
  Request_not_permitted: "Request not permitted",
  Invalid_Username_Or_Password: "Invalid Username Or Password",
  Payment_Details_Does_Not_Exists: "Payment Details Does not Exists",
  Trending_service_already_exists: "Trending service already exists",
  Popular_service_already_exists: "Popular service already exists",
  Job_Does_Not_Exist: "Job Does Not Exist",
  Career_Already_Added: "Career preferences already added for this user",
  Job_Seeker_Already_Exists: "Job Seeker Details Already Exists For This User",
  Error_Blocking_Job_Seeker: "Error in Block Job Seeker DB function",
  Job_Seeker_Deleted: "Cannot block deleted job seeker",
  Error_Initiating_Admin_Chat: "Error in initiating admin chat DB function",
  Error_Fetching_Admin_Chat: "Error in fetching admin chat DB function",
  Error_Verify_Business_Details: "Error in verify business details DB function",
  Error_Verify_Job_Seeker_Details:
    "Error in verify job seeker details DB function",
  Error_Job_Seeker_Payments_DB: "Error in Job Seeker DB",
  Error_Updating_Vendor: "Error in DB function",
  Error_Saving_Subscription_DB: "Error saving subscription in the database",
  No_Payments_Captured: "No Payments Captured",
  Invalid_User: "Invalid User",
  Invalid_Chat: "Invalid Chat",
};

module.exports.ErrorCode = {
  ApplicationError: 500,
  Invalid_Request: 501,
  Invalid_Authentication: 10003,
  Invalid_Request_Url: 10001,
  Invalid_User_Credentials: 10002,
  PhoneNo_Already_Exists: 10004,
  Email_Already_Exists: 10006,
  User_Dont_Exists: 10007,
  Review_Already_Exists: 10008,
  Review_Reply_Already_Exists: 10009,
  Saved_Service_Already_Exists: 10010,
  Package_Dont_Exists: 10011,
  Catalogue_Dont_Exists: 10012,
  No_Reviews_Found: 10013,
  No_Saved_Services_Available: 10014,
  No_Leads_Found: 10015,
  No_Vendors_Found: 10015,
  Vendor_Dont_Exists: 10016,
  Category_Already_Exists: 10017,
  Category_Dont_Exists: 10018,
  Sub_Catergory_Already_Exists: 10019,
  No_Sub_Category_Found: 10020,
  No_Service_Found: 10021,
  No_Notification_Found: 10022,
  Business_Dont_Exists: 10023,
  New_password_should_not_be_same_as_your_previous_password: 10024,
  Passwords_do_not_match: 10025,
  Old_Password_Incorrect: 10026,
  Request_not_permitted: 10027,
  Invalid_Username_Or_Password: 10028,
  Payment_Details_Does_Not_Exists: 10029,
  Trending_service_already_exists: 10030,
  Popular_service_already_exists: 10031,
  Job_Does_Not_Exist: 10032,
  Career_Already_Added: 10033,
  Job_Seeker_Already_Exists: 10034,
  Error_Blocking_Job_Seeker: 10035,
  Job_Seeker_Deleted: 10036,
  Error_Initiating_Admin_Chat: 10037,
  Error_Fetching_Admin_Chat: 10038,
  Error_Verify_Business_Details: 10039,
  Error_Verify_Job_Seeker_Details: 10040,
  Error_Job_Seeker_Payments_DB: 10041,
  Error_Updating_Vendor: 10042,
  Error_Saving_Subscription_DB: 10043,
  No_Payments_Captured: 10044,
  Invalid_User: 10045,
  Invalid_Chat: 10046,
};

module.exports.RequestType = {
  USERLOGIN: "U",
  USERLOGOUT: "UO",
  ADDUSER: "AU",
  EDITUSER: "EU",
  FETCHUSER: "FU",
  ADDADVERTISEMENT: "AD",
  ADDVENDOR: "V",
  EDITVENDOR: "EV",
  FETCHVENDOR: "FV",
  ADDREVIEW: "AR",
  FETCHREVIEWS: "FR",
  ADDREVIEWREPLY: "ARR",
  FETCHREVIEWS: "FR",
  FETCHLEADS: "FL",
  ADDSAVEDSERVICES: "ASS",
  FETCHSAVEDSERVICES: "FSS",
  ADDLEADS: "AL",
  FETCHLEADS: "FL",
  SHOWPACKAGEDETAILS: "SPD",
  PACKAGEUPDATION: "PU",
  FETCHCATALOGUE: "FC",
  SHOWBALANCEADS: "SBA",
  VENDORSCATEGORIES: "VC",
  ADDCATALOGUE: "AC",
  GETVENDORSRADIUS: "GVR",
  FILTER: "F",
  FETCHCATEGORIES: "FC",
  FETCHSUBCATEGORIES: "FS",
  FORGOTPASSWORD: "FP",
  RECENTLYADDED5: "RA5",
  RECENTLYADDEDALL: "RAA",
  ADDBUSINESSDETAILS: "ABD",
  ADDBUSINESSVERIFICATIONIMAGE: "ABVI",
  FETCHNOTIFICATIONS: "FN",
  DELETENOTIFICATIONS: "DN",
  PUSHNOTIFICATIONBYUSER: "PNU",
  PUSHNOTIFICATIONBYVENDOR: "PNV",
  FETCHBUSINESSDETAILS: "FBD",
  FETCHBUSINESSDETAILSWRTVENDOR: "FBDV",
  FETCHPOPULARSERVICES: "FP",
  FETCHTRENDINGSERVICES: "TS",
  UPDATEPASSWORD: "UP",
  SUSCRIBEPACKAGE: "SP",
  PAYMENTAPPROVAL: "PA",
  PAYMENTDETAILS: "PD",
  CHATINITAITED: "CID",
  FETCHCHATINITIATED: "FCI",
  //Admin
  ADDCATEGORIES: "AAC",
  ADDSUBCATEGORIES: "ASC",
  ADDPOPULARESERVICES: "ASP",
  ADDTRENDINGSERVICES: "ATS",
  BLOCKUNBLOCKACCOUNT: "BUA",
  DELETEREVIEW: "DR",
  APPROVEREJECTVENDORS: "ARV",
  FETCHAPPROVEDREJECTVENDORS: "FARV",
  ADDMASTER: "AM",
  FETCHREVENUEGENERAYED: "FRD",
  DELETEADVERTISEMENT: "DAD",
  FETCHDATA: "FD",
  FETCHMASTERDETAILS: "FMD",
  FETCHADVERTISEMENTS: "FD",
  DELETETRENDINGSERVICES: "DTS",
  DELETECATEGORY: "DTC",
  BUSINESSLINK: "BL",
  addAdminAdvertisement: "ADDV",
  APPROVALOFBUSINESS: "APV",
  DELETEPOPULARSERVICES: "DPS",
  ADCOMPANYDETAILS: "ACD",
  JOBNOTIFICATIONS: "JN",
};

module.exports.PaymentStates = {
  created: 1,
  authorized: 2,
  captured: 3,
  refunded: 4,
  failed: 5,
};
